/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class penjualan extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public penjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tglPPTF = new javax.swing.JTextField();
        ksPTF = new javax.swing.JTextField();
        nsPTF = new javax.swing.JTextField();
        jaPTF = new javax.swing.JTextField();
        kelasPCB = new javax.swing.JComboBox<>();
        notTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbPTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        danaBos = new javax.swing.JRadioButton();
        danaBop = new javax.swing.JRadioButton();
        bayarCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tpBTN = new javax.swing.JButton();
        eBTN = new javax.swing.JButton();
        hBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jssb = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ntTF = new javax.swing.JTextField();
        kdpbTF = new javax.swing.JTextField();
        nspbTF = new javax.swing.JTextField();
        bCB = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ntTF1 = new javax.swing.JTextField();
        kdpbTF1 = new javax.swing.JTextField();
        nspbTF1 = new javax.swing.JTextField();
        bCB1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jpTF = new javax.swing.JTextField();
        jsbTF = new javax.swing.JTextField();
        jpTF1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpTF2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jpTF3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jpTF5 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        dtRefundBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PEMBAYARAN"));

        jLabel4.setText("TGL PESAN");

        jLabel5.setText("KODE SEKOLAH");

        jLabel6.setText("NAMA SEKOLAH");

        jLabel7.setText("KELAS");

        jLabel8.setText("JUMLAH AKUN");

        tglPPTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglPPTFActionPerformed(evt);
            }
        });

        kelasPCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===Pilih===", "KELAS 4", "KELAS 5", "KELAS 6", "KELAS 8", "KELAS 10" }));

        jLabel9.setText("NO TRANSAKSI");

        jLabel10.setText("TOTAL BAYAR");

        jLabel11.setText("CARA BAYAR");

        buttonGroup1.add(danaBos);
        danaBos.setText("DANA BOS");

        buttonGroup1.add(danaBop);
        danaBop.setText("DANA BOP");

        bayarCB.setText("BAYAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ksPTF)
                            .addComponent(tglPPTF, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kelasPCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jaPTF)))
                            .addComponent(nsPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbPTF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bayarCB)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(danaBos)
                                .addGap(18, 18, 18)
                                .addComponent(danaBop)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(notTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tglPPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ksPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nsPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kelasPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jaPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tbPTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(danaBos)
                    .addComponent(danaBop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bayarCB)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DATA PENJUALAN & BERLANGGANAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("BUKU DIGITAL MATEMATIKAN - \"PT. PAMULANG STORE\"");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("By : Hibatul Akmal");

        tpBTN.setText("TAMBAH PESANAN");
        tpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpBTNActionPerformed(evt);
            }
        });

        eBTN.setText("EDIT");
        eBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBTNActionPerformed(evt);
            }
        });

        hBTN.setText("HAPUS");
        hBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hBTNActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("TAMPIL DATA PEMBAYARAN"));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO TRANSAKSI", "TGL. PESAN", "NAMA SEKOLAH", "KELAS", "JUMLAH AKUN ", "TOTAL BAYAR", "CARA PEMBAYARAN", "BANK", "STATUS BAYAR"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("JML. SEKOLAH SUDAH BAYAR");

        jssb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jssbActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("REFUND"));

        jLabel13.setText("NO TRANSAKSI");

        jLabel14.setText("NAMA SEKOLAH");

        jLabel15.setText("TOTAL BAYAR");

        bCB.setText("REFUND");
        bCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kdpbTF)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bCB)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(nspbTF)
                    .addComponent(ntTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ntTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(kdpbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nspbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCB))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("RENEWAL"));

        jLabel16.setText("NO TRANSAKSI");

        jLabel17.setText("NAMA SEKOLAH");

        jLabel18.setText("KELAS");

        bCB1.setText("RENEWAL");

        jButton1.setText("CARI");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kdpbTF1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bCB1)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(nspbTF1)
                    .addComponent(ntTF1))
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ntTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(kdpbTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nspbTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCB1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA REFUND PEMBAYARAN"));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO TRANSAKSI", "TGL PESAN", "NAMA SEKOLAH", "KELAS", "JUMLAH AKUN ", "TOTAL BAYAR", "CARA PEMBAYARAN", "BANK", "NILAI REFUND"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table2);

        jLabel19.setText("JUMLAH SELURUH REFUND");

        jLabel20.setText("TOTAL PENDAPATAN");

        jpTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpTFActionPerformed(evt);
            }
        });

        jsbTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsbTFActionPerformed(evt);
            }
        });

        jpTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpTF1ActionPerformed(evt);
            }
        });

        jLabel21.setText("JUMLAH SELURUH PEMBAYARAN");

        jLabel22.setText("JUMLAH UANG DI DKI DIS");

        jpTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpTF2ActionPerformed(evt);
            }
        });

        jLabel23.setText("JUMLAH UANG DI BCA PE");

        jpTF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpTF3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jpTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsbTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpTF2)))
                        .addGap(68, 68, 68))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jpTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jpTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jpTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jsbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA RENEWAL SEKOLAH"));

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE SEKOLAH", "NAMA SEKOLAH", "KELAS", "JUMLAH AKUN ", "RENEWAL"
            }
        ));
        jScrollPane5.setViewportView(table4);

        jLabel26.setText("JUMLAH AKUN RENEWAL");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jpTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        dtRefundBTN.setText("DATA REFUND");
        dtRefundBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtRefundBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jssb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(dtRefundBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGap(121, 121, 121))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(66, 66, 66))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tpBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hBTN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jssb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtRefundBTN))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglPPTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPPTFActionPerformed
        // TODO add your handling code here:
        Date tanggalHariIni = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String tanggalSaja = sdf.format(tanggalHariIni);
        tglPPTF.setText(tanggalSaja);
    }//GEN-LAST:event_tglPPTFActionPerformed

    private void tpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 = (DefaultTableModel)table1.getModel();

        String noTransaksi = notTF.getText();
        String tglPesan = tglPPTF.getText();
        String kodeSekolah = ksPTF.getText();
        String namaSekolah = nsPTF.getText();
        int JumlahAkun = Integer.parseInt(jaPTF.getText());
        int TotalBayar = Integer.parseInt(tbPTF.getText());
        
        String kelas = "";
        if(kelasPCB.getSelectedIndex()== 0){
            kelas = "";
        }else if(kelasPCB.getSelectedIndex()== 1){
            kelas = "KELAS 4";
        } else if(kelasPCB.getSelectedIndex()== 2){
            kelas = "KELAS 5";
        } else if(kelasPCB.getSelectedIndex()== 3){
            kelas = "KELAS 6";
        } else if(kelasPCB.getSelectedIndex()== 4){
            kelas = "KELAS 8";
        } else if(kelasPCB.getSelectedIndex()== 5){
            kelas = "KELAS 10";
        }
        String caraBayar = "";
        String bank = "";
        if(danaBos.isSelected()){
            caraBayar = "DANA BOS";
            bank = "DKI DIS";
        }else{
            caraBayar = "DANA BOP";
            bank = "BCA PE";
        }
        
        String statusBayar = "";
        if(bayarCB.isSelected()){
            statusBayar = "LUNAS";
        }else{
            statusBayar = "BELUM BAYAR";
        }
        
        tb1.addRow(new Object[]{
            (noTransaksi), (tglPesan), (namaSekolah), (kelas), (JumlahAkun), (TotalBayar), (caraBayar), (bank), (statusBayar)
        });
        

        //clear
        notTF.setText("");
        tglPPTF.setText("");
        ksPTF.setText("");
        nsPTF.setText("");
        kelasPCB.setSelectedIndex(0);
        jaPTF.setText("");
        tbPTF.setText("");
        bayarCB.setSelected(false);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_tpBTNActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int row = table1.getSelectedRow();
        if(row >= 0){
            notTF.setText(table1.getValueAt(row, 0).toString());
            tglPPTF.setText(table1.getValueAt(row, 1).toString());
            nsPTF.setText(table1.getValueAt(row, 2).toString());
            jaPTF.setText(table1.getValueAt(row, 4).toString());
            tbPTF.setText(table1.getValueAt(row, 5).toString());

            String valueToAddToComboBox = table1.getValueAt(row, 3).toString();
            DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) kelasPCB.getModel();
            model.setSelectedItem(valueToAddToComboBox);

            String radioButtonValue = table1.getValueAt(row, 7).toString();

            // Misalnya, Anda memiliki dua radio button dengan nama radioButtonYa dan radioButtonTidak
            if (radioButtonValue.equals("DKI DIS")) {
                danaBos.setSelected(true);
                danaBop.setSelected(false);
            } else if (radioButtonValue.equals("BCA PE")) {
                danaBos.setSelected(false);
                danaBop.setSelected(true);
            } else {
                // Anda dapat menentukan perilaku default jika data tidak cocok dengan pilihan yang ada
                danaBos.setSelected(false);
                danaBop.setSelected(false);
            }
            
            String checkBoxValue = table1.getValueAt(row, 8).toString();

            // Misalnya, Anda memiliki satu JCheckBox dengan nama checkBox1
            if (checkBoxValue.equals("LUNAS")) {
                bayarCB.setSelected(true);
            } else if (checkBoxValue.equals("“BELUM BAYAR")) {
                bayarCB.setSelected(false);
            } else {
                // Anda dapat menentukan perilaku default jika data tidak cocok dengan pilihan yang ada
                bayarCB.setSelected(false);
            }
        }

    }//GEN-LAST:event_table1MouseClicked

    private void hBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 = (DefaultTableModel) table1.getModel();
                int selectedRow = table1.getSelectedRow();
                if (selectedRow != -1) {
                    tb1.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(null, "Hapus Data", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                    notTF.setText("");
                    tglPPTF.setText("");
                    ksPTF.setText("");
                    nsPTF.setText("");
                    kelasPCB.setSelectedIndex(0);
                    jaPTF.setText("");
                    tbPTF.setText("");
                    bayarCB.setSelected(false);
                    buttonGroup1.clearSelection();
                } else {
                    JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus.");
                }
    }//GEN-LAST:event_hBTNActionPerformed

    private void jssbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jssbActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 = (DefaultTableModel) table1.getModel();
        int rowCount = tb1.getRowCount();
        int totalLunas = 0;

        for (int i = 0; i < rowCount; i++) {
            String statusBayar = (String) tb1.getValueAt(i, 8); // Mengambil status bayar dari kolom ke-6

            // Periksa apakah status bayar adalah "LUNAS"
            if ("LUNAS".equals(statusBayar)) {
                totalLunas++; // Menambah jumlah baris yang memiliki status "LUNAS"
            }
        }

        jssb.setText(String.valueOf(totalLunas));
    }//GEN-LAST:event_jssbActionPerformed

    private void eBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)table1.getModel();
        
        int row = table1.getSelectedRow();
        if(row >= 0){
            String noTransaksi = notTF.getText();
            String tglPesan = tglPPTF.getText();
            String namaSekolah = nsPTF.getText();
            int JumlahAkun = Integer.parseInt(jaPTF.getText());
            int TotalBayar = Integer.parseInt(tbPTF.getText());

            String kelas = "";
            if(kelasPCB.getSelectedIndex()== 0){
                kelas = "";
            }else if(kelasPCB.getSelectedIndex()== 1){
                kelas = "KELAS 4";
            } else if(kelasPCB.getSelectedIndex()== 2){
                kelas = "KELAS 5";
            } else if(kelasPCB.getSelectedIndex()== 3){
                kelas = "KELAS 6";
            } else if(kelasPCB.getSelectedIndex()== 4){
                kelas = "KELAS 8";
            } else if(kelasPCB.getSelectedIndex()== 5){
                kelas = "KELAS 10";
            }
            String caraBayar = "";
            String bank = "";
            if(danaBos.isSelected()){
                caraBayar = "DANA BOS";
                bank = "DKI DIS";
            }else{
                caraBayar = "DANA BOP";
                bank = "BCA PE";
            }

            String statusBayar = "";
            if(bayarCB.isSelected()){
                statusBayar = "LUNAS";
            }else{
                statusBayar = "BELUM BAYAR";
            }
            
            table.setValueAt(noTransaksi, row, 0);
            table.setValueAt(tglPesan, row, 1);
            table.setValueAt(namaSekolah, row, 2);
            table.setValueAt(kelas, row, 3);
            table.setValueAt(JumlahAkun, row, 4);
            table.setValueAt(TotalBayar, row, 5);
            table.setValueAt(caraBayar, row, 6);
            table.setValueAt(bank, row, 7);
            table.setValueAt(statusBayar, row, 8);
        }
    }//GEN-LAST:event_eBTNActionPerformed

    private void dtRefundBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtRefundBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1 = (DefaultTableModel)table1.getModel();
        DefaultTableModel tb2 = (DefaultTableModel)table2.getModel();
        for (int i = 0; i < tb1.getRowCount(); i++) {
            String statusBayar = (String) tb1.getValueAt(i, 8);
            if (statusBayar.equals("LUNAS")) {
                Object[] rowData = new Object[8];
                for (int j = 0; j < 8; j++) {
                    rowData[j] = tb1.getValueAt(i, j);
                }
                tb2.addRow(rowData);
                tb1.removeRow(i);
                i--; // Perbarui indeks setelah menghapus baris
            }
        }
    }//GEN-LAST:event_dtRefundBTNActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        int row = table2.getSelectedRow();
        if(row >= 0){
            ntTF.setText(table2.getValueAt(row, 0).toString());
            kdpbTF.setText(table2.getValueAt(row, 2).toString());
            nspbTF.setText(table2.getValueAt(row, 5).toString());            
        }
    }//GEN-LAST:event_table2MouseClicked

    private void bCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCBActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb2 = (DefaultTableModel)table2.getModel();
        int selectedRow = table2.getSelectedRow();

        if(bCB.isSelected()){
            if (selectedRow != -1) {
                String totalBayar = nspbTF.getText();
                int totalBayarInt = Integer.parseInt(totalBayar);

                double totalRefund = 0.15 * totalBayarInt;                
                tb2.setValueAt(totalRefund, selectedRow, 8);
                
                //clear
                ntTF.setText("");
                kdpbTF.setText("");
                nspbTF.setText("");
                bCB.setSelected(false);
            }
        }

    }//GEN-LAST:event_bCBActionPerformed

    private void jpTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpTF1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb2 = (DefaultTableModel) table2.getModel();
        int rowCount = tb2.getRowCount();
        int total = 0;
        for (int i = 0; i < rowCount; i++) {
            int formattedValue = (int) tb2.getValueAt(i, 5);
            total += formattedValue;
        }
        jpTF1.setText(""+total);
    }//GEN-LAST:event_jpTF1ActionPerformed

    private void jpTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpTFActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb2 = (DefaultTableModel) table2.getModel();
        int rowCount = tb2.getRowCount();
        int total = 0;
        for (int i = 0; i < rowCount; i++) {
            double formattedValue = (double) tb2.getValueAt(i, 8);
            total += formattedValue;
        }
        jpTF.setText(""+total);
    }//GEN-LAST:event_jpTFActionPerformed

    private void jsbTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsbTFActionPerformed
        // TODO add your handling code here:
        double TotalPem = Double.parseDouble(jpTF1.getText());
        double TotalRef = Double.parseDouble(jpTF.getText());
        
        double TotalPen = TotalPem - TotalRef;
        jsbTF.setText("" + TotalPen);
    }//GEN-LAST:event_jsbTFActionPerformed

    private void jpTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpTF2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb2 = (DefaultTableModel) table2.getModel();
        int rowCount = tb2.getRowCount();
        int totalDki = 0;
        for (int i = 0; i < rowCount; i++) {
            String dki = (String) tb2.getValueAt(i, 7);
            if ("DKI DIS".equals(dki)) {
                double formattedValue = (double) tb2.getValueAt(i, 8);
                totalDki += formattedValue;
            } 
        }
        jpTF2.setText(""+totalDki);
    }//GEN-LAST:event_jpTF2ActionPerformed

    private void jpTF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpTF3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb2 = (DefaultTableModel) table2.getModel();
        int rowCount = tb2.getRowCount();
        int totalBca = 0;
        for (int i = 0; i < rowCount; i++) {
            String bca = (String) tb2.getValueAt(i, 7);
            if ("BCA PE".equals(bca)) {
                double formattedValue = (double) tb2.getValueAt(i, 8);
                totalBca += formattedValue;
            } 
        }
        jpTF3.setText(""+totalBca);
    }//GEN-LAST:event_jpTF3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bCB;
    private javax.swing.JCheckBox bCB1;
    private javax.swing.JCheckBox bayarCB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton danaBop;
    private javax.swing.JRadioButton danaBos;
    private javax.swing.JButton dtRefundBTN;
    private javax.swing.JButton eBTN;
    private javax.swing.JButton hBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jaPTF;
    private javax.swing.JTextField jpTF;
    private javax.swing.JTextField jpTF1;
    private javax.swing.JTextField jpTF2;
    private javax.swing.JTextField jpTF3;
    private javax.swing.JTextField jpTF5;
    private javax.swing.JTextField jsbTF;
    private javax.swing.JTextField jssb;
    private javax.swing.JTextField kdpbTF;
    private javax.swing.JTextField kdpbTF1;
    private javax.swing.JComboBox<String> kelasPCB;
    private javax.swing.JTextField ksPTF;
    private javax.swing.JTextField notTF;
    private javax.swing.JTextField nsPTF;
    private javax.swing.JTextField nspbTF;
    private javax.swing.JTextField nspbTF1;
    private javax.swing.JTextField ntTF;
    private javax.swing.JTextField ntTF1;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table4;
    private javax.swing.JTextField tbPTF;
    private javax.swing.JTextField tglPPTF;
    private javax.swing.JButton tpBTN;
    // End of variables declaration//GEN-END:variables
}
